// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umtpttbwcgonyfkvprio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtdHB0dGJ3Y2dvbnlma3ZwcmlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjA3MDcsImV4cCI6MjA2NTQ5NjcwN30.nb6-AYKGLU1MfyCVT45tEXF8r1H9y30EknKiQt-v1TU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);